mysql:
    read:
        Host: 127.0.0.1:3306
        User: root
        Pass: 123456
        Name: "go_pro"
    write:
        Host: 127.0.0.1:3306
        User: root
        Pass: 123456
        Name: "go_pro"

