mysql:
    base:
        maxidleconn = 10
        maxopenconn = 100
        connmaxlifetime = 10
    read:
        Host: 43.139.144.28:3308
        User: root
        Pass: peng12345
        Name: "go_pro"
    write:
        Host: 43.139.144.28:3307
        User: root
        Pass: peng12345
        Name: "go_pro"
jwtpass: "OrmsUCgCJnyuidlk"
redis:
    dbaddr: 43.139.144.28:6380
    dbpass: peng12345
    db: "0"
    maxretries: 3
    poolsize: 10
    minidleconns: 5
